### ISSUE TITLE
Task priority with AT example

### ISSUE THREAD

**Issue by Karang** [espressif/ESP8266_AT#3]
Hi,
I've tried to edit the AT example, by adding the loop code given in the basic example (taken from here : https://github.com/esp8266/source-code-examples ).

Because the uart use task priorities 0 and 1, I've been trying to use USER_TASK_PRIO_2.

But the task seems to never be called. If i use USER_TASK_PRIO_0 the task is called, but as expected the uart don't work well.

Any idea ?

**Comment by atdeveloper** [comment]
At present, only allows using two user tasks, and in example the two 
tasks has been used.

于 2014/12/1 18:36, Arthur Hennequin 写道:

> tried to edit the AT example, by adding the loop code given in the 
> basic example (taken from here

**Comment by Karang** [comment]
Thank you.
I will try to use only 1 task priority for uart and main loop, with different signals.
