### ISSUE TITLE
Transparent mode when using the module as Server

### ISSUE THREAD

**Issue by garyservin** [espressif/ESP8266_AT#4]
The ESP8266 is an awesome module! I just have one question.

Is there a specific reason why the transparent mode is disabled when using the module as a server? https://github.com/espressif/esp8266_at/blob/master/at/user/at_ipCmd.c#L1371

**Comment by atdeveloper** [comment]
Ha-ha, it's funy.
Ok, give some advice.
When server in the transparent, maybe only allows one client to link.
Please use "espconn_tcp_get_max_con_allow" to limit the link number.
Of course, if close server or return to normal(quit transparent, CIPMODE 
= 0), should restore the default value(5 links).

Pergaps you have a better idea.

Welcome to upload your modify code.

于 2014/12/1 22:09, Gary Servin 写道:

**Comment by atdeveloper** [comment]
Sorry, made a mistake, not "espconn_tcp_get_max_con_allow" but 
"espconn_tcp_set_max_con_allow"
于 2014/12/2 9:55, XuJingjie 写道:

**Comment by tprochazka** [comment]
Why you closed the issue? Transparent mode in server mode is possible without your modification?
