### ISSUE TITLE
User task and wifi

### ISSUE THREAD

**Issue by Karang** [espressif/ESP8266_AT#5]
Hi,
I've noticed that when I run a user task (like this : https://github.com/Karang/Ardunet/blob/master/src/user/user_main.cpp#L49-L62), the wifi doesn't work anymore (In station and AP mode). Is there a particular reason?
Where can I find the internal architecure of the esp8266 ? I would like to understand how tasks are implemented on the chip.
Regards

**Comment by atdeveloper** [comment]
Hi,
The base OS didn't open source, it’s a non preemptive os, it didn't go to the higher priority tasks in the delay. 
I saw two delay in loop function, maybe the task take up too much time.
Please minimize using delay. 
If you want to use PWM, please look at pwm example in "iot_demo".
If you developing base on sdk, recommend using the new SDK (https://github.com/espressif/esp_iot_rtos_sdk_lib).
It‘s based on freertos.
Regards.

**Comment by Karang** [comment]
Thank you for your quick answer ;)
I'll look into the RTOS SDK.
