### ISSUE TITLE
Operating mode reverts back to 3(softAP+station) after restart

### ISSUE THREAD

**Issue by sschocke** [espressif/ESP8266_AT#8]
I am not sure if this is the desired behavior of the module or not, but after setting the operating mode via AT+CWMODE=2, and issuing AT+RST a while later(or power cycling the module), the operating mode automatically reverts back to 3(softAP+station)

I tried to have a look at the code here to see how the SSID is saved, but it seems this is handled automatically by the SDK.

**Comment by AthenaYu** [comment]
I tried it ，it is fine..

AT+CWMODE=3

OK
AT+RST

OK

 ets Jan  8 2013,rst cause:4, boot mode:(3,3)

wdt reset
load 0x40100000, len 612, room 16 
tail 4
chksum 0x12
load 0x3ffe8000, len 788, room 4 
tail 0
chksum 0x50
load 0x3ffe8314, len 264, room 8 
tail 0
chksum 0x4a
csum 0x4a

2nd boot version : 1.1
  SPI Speed      : 40MHz
  SPI Mode       : QIO
  SPI Flash Size : 4Mbit
jump to run user1

sƒ
ready
AT+CWMODE?
+CWMODE:3

OK

**Comment by AthenaYu** [comment]
I tried it, it is fine..
AT+CWMODE?
+CWMODE:3

OK
AT+CWMODE=2

OK
AT+RST

OK

 ets Jan  8 2013,rst cause:4, boot mode:(3,3)

wdt reset
load 0x40100000, len 612, room 16 
tail 4
chksum 0x12
load 0x3ffe8000, len 788, room 4 
tail 0
chksum 0x50
load 0x3ffe8314, len 264, room 8 
tail 0
chksum 0x4a
csum 0x4a

2nd boot version : 1.1
  SPI Speed      : 40MHz
  SPI Mode       : QIO
  SPI Flash Size : 4Mbit
jump to run user1

rƒ
ready
AT+CWMODE?
+CWMODE:2

OK

**Comment by sschocke** [comment]
yes, sorry about that... it was a long lost piece of my own code that was resetting it during startup, not the module itself. thanks for looking into it though.
